<?php

namespace ContainerOlbT71E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIngredientsApiControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YbgLJuC.App\Controller\API\IngredientsApiController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YbgLJuC.App\\Controller\\API\\IngredientsApiController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\IngredientsRepository', 'getIngredientsRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'repository' => 'App\\Repository\\IngredientsRepository',
            'em' => '?',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\API\\IngredientsApiController::edit()', $container);
    }
}
