<?php

namespace ContainerOlbT71E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiaisonPlatIngredientsApiControllermakeRecetteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KulH94z.App\Controller\API\LiaisonPlatIngredientsApiController::makeRecette()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KulH94z.App\\Controller\\API\\LiaisonPlatIngredientsApiController::makeRecette()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\LiaisonPlatIngredientsRepository', 'getLiaisonPlatIngredientsRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'platRepo' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
            'ingRepo' => ['privates', 'App\\Repository\\IngredientsRepository', 'getIngredientsRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\LiaisonPlatIngredientsRepository',
            'em' => '?',
            'platRepo' => 'App\\Repository\\PlatRepository',
            'ingRepo' => 'App\\Repository\\IngredientsRepository',
        ]))->withContext('App\\Controller\\API\\LiaisonPlatIngredientsApiController::makeRecette()', $container);
    }
}
