<?php

namespace ContainerOlbT71E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiaisonPlatIngredientsApiControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W1Jq481.App\Controller\API\LiaisonPlatIngredientsApiController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W1Jq481.App\\Controller\\API\\LiaisonPlatIngredientsApiController::detail()'] = ($container->privates['.service_locator.W1Jq481'] ?? $container->load('get_ServiceLocator_W1Jq481Service'))->withContext('App\\Controller\\API\\LiaisonPlatIngredientsApiController::detail()', $container);
    }
}
