<?php

namespace ContainerOlbT71E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l29yt7Y.App\Controller\ProjectController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l29yt7Y.App\\Controller\\ProjectController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'project' => ['privates', '.errored..service_locator.l29yt7Y.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.l29yt7Y": it needs an instance of "App\\Entity\\Project" but this type has been excluded in "config/services.yaml".'],
            'deleteService' => ['privates', 'App\\Service\\DeleteService', 'getDeleteServiceService', true],
        ], [
            'project' => 'App\\Entity\\Project',
            'deleteService' => 'App\\Service\\DeleteService',
        ]))->withContext('App\\Controller\\ProjectController::delete()', $container);
    }
}
