<?php

namespace ContainerOlbT71E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatApiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kLBGC1j.App\Controller\API\PlatApiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kLBGC1j.App\\Controller\\API\\PlatApiController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deleteService' => ['privates', 'App\\Service\\DeleteService', 'getDeleteServiceService', true],
            'repository' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
        ], [
            'deleteService' => 'App\\Service\\DeleteService',
            'repository' => 'App\\Repository\\PlatRepository',
        ]))->withContext('App\\Controller\\API\\PlatApiController::delete()', $container);
    }
}
