<?php

namespace ContainerOlbT71E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatApiControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DLQ99Ys.App\Controller\API\PlatApiController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DLQ99Ys.App\\Controller\\API\\PlatApiController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
        ], [
            'em' => '?',
            'serializer' => '?',
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
        ]))->withContext('App\\Controller\\API\\PlatApiController::create()', $container);
    }
}
