<?php

namespace ContainerOlbT71E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8GJsi_3.App\Controller\UserController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8GJsi_3.App\\Controller\\UserController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.8GJsi_3.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.8GJsi_3": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'deleteService' => ['privates', 'App\\Service\\DeleteService', 'getDeleteServiceService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'deleteService' => 'App\\Service\\DeleteService',
        ]))->withContext('App\\Controller\\UserController::delete()', $container);
    }
}
