<?php

namespace ContainerHbcqhKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_B_CHR4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.b.CH_R4' shared service.
     *
     * @return \App\Controller\API\PlatRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\API\\LiaisonPlatIngredientsApiController::makeRecette()": the $platRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\API\\PlatRepository". Did you forget to add a use statement?');
    }
}
