<?php

namespace ContainerHbcqhKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIngredientsApiControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rPALwq0.App\Controller\API\IngredientsApiController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rPALwq0.App\\Controller\\API\\IngredientsApiController::list()'] = ($container->privates['.service_locator.rPALwq0'] ?? $container->load('get_ServiceLocator_RPALwq0Service'))->withContext('App\\Controller\\API\\IngredientsApiController::list()', $container);
    }
}
