<?php

namespace ContainerHbcqhKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIngredientsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SwWgpyy.App\Entity\Ingredients' shared service.
     *
     * @return \App\Entity\Ingredients
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SwWgpyy": it needs an instance of "App\\Entity\\Ingredients" but this type has been excluded in "config/services.yaml".');
    }
}
