<?php

namespace ContainerHbcqhKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIngredientsApiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4CzP2VX.App\Controller\API\IngredientsApiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4CzP2VX.App\\Controller\\API\\IngredientsApiController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'deleteService' => ['privates', 'App\\Service\\DeleteService', 'getDeleteServiceService', true],
            'repository' => ['privates', 'App\\Repository\\IngredientsRepository', 'getIngredientsRepositoryService', true],
        ], [
            'deleteService' => 'App\\Service\\DeleteService',
            'repository' => 'App\\Repository\\IngredientsRepository',
        ]))->withContext('App\\Controller\\API\\IngredientsApiController::delete()', $container);
    }
}
