<?php

namespace ContainerHbcqhKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiaisonPlatIngredientsApiControllermakeRecetteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xlPjKa1.App\Controller\API\LiaisonPlatIngredientsApiController::makeRecette()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xlPjKa1.App\\Controller\\API\\LiaisonPlatIngredientsApiController::makeRecette()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\LiaisonPlatIngredientsRepository', 'getLiaisonPlatIngredientsRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'platRepo' => ['privates', '.errored.b.CH_R4', NULL, 'Cannot determine controller argument for "App\\Controller\\API\\LiaisonPlatIngredientsApiController::makeRecette()": the $platRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\API\\PlatRepository". Did you forget to add a use statement?'],
            'ingRepo' => ['privates', '.errored.3ZchlFQ', NULL, 'Cannot determine controller argument for "App\\Controller\\API\\LiaisonPlatIngredientsApiController::makeRecette()": the $ingRepo argument is type-hinted with the non-existent class or interface: "App\\Controller\\API\\IngredientsRepository". Did you forget to add a use statement?'],
        ], [
            'repository' => 'App\\Repository\\LiaisonPlatIngredientsRepository',
            'em' => '?',
            'platRepo' => '?',
            'ingRepo' => '?',
        ]))->withContext('App\\Controller\\API\\LiaisonPlatIngredientsApiController::makeRecette()', $container);
    }
}
