<?php

namespace ContainerHbcqhKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Ep.Tvf.App\Controller\ProjectController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Ep.Tvf.App\\Controller\\ProjectController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'repository' => 'App\\Repository\\ProjectRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ProjectController::index()', $container);
    }
}
