<?php

namespace ContainerHbcqhKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatApiControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.apVT1...App\Controller\API\PlatApiController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.apVT1...App\\Controller\\API\\PlatApiController::list()'] = ($container->privates['.service_locator.apVT1..'] ?? $container->load('get_ServiceLocator_ApVT1__Service'))->withContext('App\\Controller\\API\\PlatApiController::list()', $container);
    }
}
