<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOlbT71E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlbT71E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOlbT71E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOlbT71E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOlbT71E\App_KernelDevDebugContainer([
    'container.build_hash' => 'OlbT71E',
    'container.build_id' => '4b4fabc7',
    'container.build_time' => 1738168739,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlbT71E');
